# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84b886b4b2bbee6d723f1de43cd9cd36acee87fe748a9e35e639921864cd73e698c8528ef24ba907d4aa1df4ab0ca4c3ec19c32600f5e3fd868c6c178e00d3f

test:
  secret_key_base: 9c41baa5e441e87446eddd1cf246af9cd8da445d00f0ffe508cf27f584229acb7f5e9e2480b99d06354292f941afd28a7299ee249195c8ef4876f3e187490a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
